== Apache Maven: Profiles

Создание различных *profiles*.

== Specification of task 1

Создать класс `Calculator`, где реализованы основные арифметические операторы.

== Specification of task 2

Настроить `maven-checkstyle-plugin`, который отрабатывает на *phase* `compile`.

Для того, что бы убедиться в его работоспособности, нужно сгенерировать отчёт, в который должен быть включен класс `Calculator`.

== Specification of task 3

Настроить `maven-jacoco-plugin`, который отрабатывает на *phase* `test`.

Для того, что бы убедиться в его работоспособности, нужно сгенерировать отчёт, в который должен быть включен класс `Calculator`.

== Specification of task 4

Сконфигурировать два профиля:

* `dev` - содержит плагин `maven-checkstyle-plugin`
* `stage` - содержит плагин `maven-jacoco-plugin`

== Specification of task 5

Сделать *build* проекта используя различные профили. Убедиться, что используются только настроенные в профиле плагины.

== Specification of task 6

Сделать *build* проекта используя оба профиля одновременно.
